function main() {
  let empData = [
    {
      id: 1,
      name: "Amit Sharma",
      age: 29,
      email: "amit.sharma@example.com",
      salary: 52000,
      department: "IT",
      designation: "Frontend Developer",
      joiningDate: "2021-04-15",
    },
    {
      id: 2,
      name: "Priya Verma",
      age: 32,
      email: "priya.verma@example.com",
      salary: 68000,
      department: "HR",
      designation: "HR Manager",
      joiningDate: "2019-09-10",
    },
    {
      id: 3,
      name: "Rohit Mehta",
      age: 26,
      email: "rohit.mehta@example.com",
      salary: 45000,
      department: "Finance",
      designation: "Accountant",
      joiningDate: "2022-01-20",
    },
    {
      id: 4,
      name: "Sneha Kapoor",
      age: 28,
      email: "sneha.kapoor@example.com",
      salary: 58000,
      department: "Marketing",
      designation: "Digital Marketer",
      joiningDate: "2020-07-05",
    },
    {
      id: 5,
      name: "Arjun Singh",
      age: 35,
      email: "arjun.singh@example.com",
      salary: 75000,
      department: "Operations",
      designation: "Operations Manager",
      joiningDate: "2018-11-12",
    },
    {
      id: 6,
      name: "Riya Malhotra",
      age: 24,
      email: "riya.malhotra@example.com",
      salary: 40000,
      department: "IT",
      designation: "UI/UX Designer",
      joiningDate: "2023-03-01",
    },
    {
      id: 7,
      name: "Karan Patel",
      age: 31,
      email: "karan.patel@example.com",
      salary: 62000,
      department: "Sales",
      designation: "Sales Executive",
      joiningDate: "2020-02-14",
    },
    {
      id: 8,
      name: "Neha Gupta",
      age: 27,
      email: "neha.gupta@example.com",
      salary: 54000,
      department: "Customer Support",
      designation: "Support Engineer",
      joiningDate: "2021-10-28",
    },
    {
      id: 9,
      name: "Vikram Roy",
      age: 33,
      email: "vikram.roy@example.com",
      salary: 70000,
      department: "IT",
      designation: "Backend Developer",
      joiningDate: "2019-06-18",
    },
    {
      id: 10,
      name: "Tanya Desai",
      age: 30,
      email: "tanya.desai@example.com",
      salary: 60000,
      department: "Admin",
      designation: "Admin Officer",
      joiningDate: "2020-12-03",
    },
  ];

  let containerElem = document.getElementById("container");
  
  for (let emp of empData) {
    containerElem.innerHTML += "<div class='card'><h3>"+emp.name+"</h3><h4>"+emp.email+"</h4>  <strong><mark>"+emp.designation+"</mark><div>Department: "+emp.department+" </div></strong></div>";
  }//for
}
